spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/,file:/Users/daniel/uploads
app:
  storage:
    location: /Users/daniel/uploads
