spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filmclub
    username: root
    password: daniel
  liquibase:
    contexts: prod
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/,file:/Users/daniel/uploads
app:
  storage:
    location: /Users/daniel/uploads
