spring:
  datasource:
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  liquibase:
    contexts: prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/,file:/tmp/uploads
app:
  storage:
    location: /tmp/uploads